# Generated by Django 4.2.16 on 2024-11-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_reservation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('technician', 'Technician')], max_length=20),
        ),
    ]
